### ISSUE TITLE
Square that does nothing

### ISSUE THREAD

**Issue by veronikajsk** [nomin-project/nomin#6]
as you can see in the picture 
@ mac os x el capitan 10.11.4

![snimek obrazovky 2017-12-05 v 16 47 41](https://user-images.githubusercontent.com/24274258/33616167-6f9fef34-d9dc-11e7-8e1c-7417022b557c.png)

**Comment by agajdosi** [comment]
Should be fixed now by #17. Thank you for the report, @veronikajsk.
